### ISSUE TITLE
Welcome MSG

### ISSUE THREAD

**Issue by Minners** [Lubenica98/FairPlayMinecraft#73] opened 2017-02-18 17:01 UTC
The Welcome MSG is not sorted its completly random in wich order the mesages came

**Comment by Lubenica98** [comment] 2017-02-18 17:03
Did you try to restart the server?

**Comment by Lubenica98** [comment] 2017-02-18 22:04
I couldn't reproduce the issue you described, please give me more information.
Thanks!

**Comment by Minners** [comment] 2017-02-20 20:50
also my welcome.txt is in this example

`msg1
msg2
msg3
msg4
msg5`

but when i join on the server its completly random

`msg5
msg3
msg4
msg2
msg1`

every time its in a other order

**Comment by Minners** [comment] 2017-02-20 20:50
PS: every msg# is a single line

**Comment by Lubenica98** [comment] 2017-02-20 20:51
Please give me your config.yml and welcome.txt file.

**Comment by Minners** [comment] 2017-02-22 11:41
Server IP: bytim0.de (its a German Server) [whitelist is offline you can join by yourself]

welcome.txt | https://hastebin.com/ogomipovof.pas
config.yml | https://hastebin.com/wuzojasaju.bash

Join 1 | http://prntscr.com/ebyi9j
Join 2 | http://prntscr.com/ebying
Join 3 | http://prntscr.com/ebyivo

**Comment by Lubenica98** [comment] 2017-02-24 18:57
Thank you very much, it has been fixed in the upcoming version!

**Closed by Lubenica98** 2017-02-24 18:57 UTC
